# Generated by Django 3.1.5 on 2021-01-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='topic',
        ),
    ]
