# Generated by Django 3.1.5 on 2021-01-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210114_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posts',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='article_default_news',
            field=models.BooleanField(default=False),
        ),
    ]
