# Generated by Django 3.1.6 on 2021-05-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted_response',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted', to=settings.AUTH_USER_MODEL, verbose_name='принятые'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='tag', related_name='categories', to='posts.Category', verbose_name='категории'),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikers',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislikers', to=settings.AUTH_USER_MODEL, verbose_name='Не понравилось'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='posts.PostPhoto'),
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось'),
        ),
        migrations.AddField(
            model_name='post',
            name='response',
            field=models.ManyToManyField(blank=True, null=True, related_name='response', to=settings.AUTH_USER_MODEL, verbose_name='отклики'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='posts.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_dislikers',
            field=models.ManyToManyField(blank=True, null=True, related_name='com_dislikers', to=settings.AUTH_USER_MODEL, verbose_name='Не понравилось'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='com_likers', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='user1'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='user2'),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='subscribers'),
        ),
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
    ]
