# Generated by Django 3.1.5 on 2021-01-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210116_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='com_rate',
            new_name='com_raiting',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rate',
            new_name='post_raiting',
        ),
    ]
