# Generated by Django 3.1.5 on 2021-01-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210116_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_rate',
            new_name='author_raiting',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='article_default_news',
        ),
    ]
